Repository jenkins-x-plugins/jx-slack, pull requests merged in 2020-03, with the labels that each got.

#10 chore: lets move the go mod download earlier in the build so we have …
  Makefile
Labels: approved, size/XS

#11 feat: lets watch SlackBot resources so we dont need to restart the pod to get SlackBot CRD changes
  .secrets.baseline
  build-deploy.sh
  go.mod
  go.sum
  pkg/slackbot/activity.go
  pkg/slackbot/bot.go
  pkg/slackbot/cmd/run.go
  pkg/slackbot/factory.go
  pkg/slackbot/factory_test.go
  pkg/slackbot/prow.go
  pkg/slackbot/slack_test.go
  pkg/slackbot/users.go
Labels: size/L

#14 fix: searching for pipeline activities using labels fixes: #13
  pkg/slackbot/activity.go
  pkg/slackbot/bot.go
  pkg/slackbot/cmd/run.go
  pkg/slackbot/factory.go
  pkg/slackbot/factory_test.go
Labels: approved, size/L

#17 fix: lets show all the pipeline activity steps
  .secrets.baseline
  go.mod
  go.sum
  jenkins-x.yml
  pkg/slackbot/activity.go
  pkg/slackbot/bot.go
  pkg/slackbot/bot_test.go
  pkg/slackbot/test_data/bot/stage_multiple_steps.yaml
Labels: approved, size/L

#19 lets tidy up the slack messages and only notify interesting user defined pipeline steps
  build-deploy.sh
  charts/slack/templates/slack-users-secret.yaml
  pkg/slackbot/bot.go
  pkg/slackbot/bot_test.go
  pkg/slackbot/mappings.go
  pkg/slackbot/util.go
Labels: size/L

#21 docs: add info on installing and configuring the app
  README.md
  charts/slack/templates/deployment.yaml
  charts/slack/values.schema.json
  charts/slack/values.yaml
  docs/images/create_app.png
  docs/images/oauth.png
  docs/images/scopes.png
Labels: size/L

#22 docs: add screenshots of slack bot features
  README.md
  docs/images/dm.png
  docs/images/room.png
Labels: approved, size/S

#23 fix: missing role permissions
  charts/slack/templates/role.yaml
  charts/slack/values.yaml
Labels: size/L
