Repository jenkins-x-plugins/jx-slack, pull requests merged in 2022-09, with the labels that each got.

#52 chore: upgrade gitops to support nested gitlab repository
  Dockerfile
  go.mod
  go.sum
Labels: approved, size/S

#51 feat: add supply chain security
  .gitignore
  .goreleaser.yml
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/S, ok-to-test

#53 refactor: upgrade go version to 1.18.6
  Makefile
  go.mod
  go.sum
Labels: approved, size/XXL
